<slot />

<style lang="scss" global>
  // a reset //

  :root {
    // fonts //
    --ff-body: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
      Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    // https://modernfontstacks.com/
    --ff-mono: ui-monospace, "Source Code Pro", Menlo, Consolas,
      "DejaVu Sans Mono", monospace;
    font-family: var(--ff-body);
    // from https://utopia.fyi/type/calculator/?c=320,12,1.2,1080,20,1.333,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12
    // can set everything else based on rem/em, don't need the others.
    // also like the relative scale better with rem/ems instead of the given scales.
    font-size: clamp(1rem, 14.608px + 0.4348vw, 1.25rem);
    line-height: 1.25;

    font-synthesis: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-text-size-adjust: 100%;

    box-sizing: border-box;

    tab-size: 4;
  }

  *,
  *::before,
  *::after {
    box-sizing: inherit;
    margin: 0;
    padding: 0;

    // break very long words if necessary
    overflow-wrap: break-word;
  }

  code {
    font-family: var(--ff-mono);
  }

  input,
  button {
    font: inherit;
    color: inherit;

    border: none;
    background-color: transparent;
    // use outline transparent instead of none for better accessibility on high contrast mode
    outline: transparent;

    &:focus-visible {
      outline: var(--outline);
      outline-offset: 2px;
    }
  }

  button {
    display: inline-grid;
    place-content: center;
    padding: 0.5rem;

    &:hover {
      background-color: var(--overlay-light);
    }
  }

  // https://gist.github.com/palashmon/35bda7887eb4bc45459d71eca3dda7a5
  // https://youtu.be/345V2MU3E_w
  img,
  picture,
  video {
    max-width: 100%;
    height: auto;
    vertical-align: middle;
    font-style: italic;
    background-repeat: no-repeat;
    background-size: cover;
    shape-margin: 1rem;
  }

  // prettier-ignore
  h1, h2, h3, h4, h5, h6 {
    font-family: var(--ff-heading);
    font-weight: 800;
    // prevent large difference in line lengths
    text-wrap: balance;
    // slightly shorter line height than default 1.5
    line-height: 1.25;
  }

  a {
    color: var(--blue);

    &:visited {
      color: var(--purple);
    }

    &:hover,
    &:focus {
      text-decoration-thickness: 3px;
    }

    &:focus-visible {
      outline: var(--outline);
      outline-offset: 2px;
    }
  }

  // override links on headings
  :is(h1, h2, h3, h4, h5, h6) a {
    text-decoration: none;
    color: inherit;

    &:hover,
    &:focus {
      text-decoration: underline;
    }

    &:visited {
      color: inherit;
    }
  }

  p,
  li {
    // prevent orphan words
    text-wrap: pretty;
  }

  h1 {
    font-size: var(--fs-7);
    letter-spacing: 0.02em;
  }

  h2 {
    font-size: var(--fs-6);
  }

  h3 {
    font-size: var(--fs-5);
  }

  // scrollbars //
  ::-webkit-scrollbar {
    width: var(--scrollbar-size);
    height: var(--scrollbar-size);
  }

  ::-webkit-scrollbar-thumb {
    background-color: var(--color-surface-container-high);
    border-radius: var(--scrollbar-size);

    transition: background-color var(--time-transition);

    &:hover {
      background-color: var(--color-surface-container-highest);
    }

    &:active {
      background-color: var(--color-inverse-primary);
    }
  }

  ::-webkit-scrollbar-track,
  ::-webkit-scrollbar-corner {
    background-color: var(--color-surface1);
  }

  *::selection {
    background-color: var(--color-primary);
    color: var(--color-on-primary);
  }

  // variables //

  // generated by material theme builder
  // https://www.figma.com/community/plugin/1034969338659738588/material-theme-builder
  :root {
    --color-primary: rgb(255 176 200);
    --color-surface-tint: rgb(255 176 200);
    --color-on-primary: rgb(84 29 50);
    --color-primary-container: rgb(112 51 73);
    --color-on-primary-container: rgb(255 217 226);
    --color-secondary: rgb(227 189 198);
    --color-on-secondary: rgb(66 41 49);
    --color-secondary-container: rgb(90 63 71);
    --color-on-secondary-container: rgb(255 217 226);
    --color-tertiary: rgb(239 189 148);
    --color-on-tertiary: rgb(72 41 12);
    --color-tertiary-container: rgb(98 63 32);
    --color-on-tertiary-container: rgb(255 220 193);
    --color-error: rgb(255 180 171);
    --color-on-error: rgb(105 0 5);
    --color-error-container: rgb(147 0 10);
    --color-on-error-container: rgb(255 218 214);
    --color-background: rgb(25 17 19);
    --color-on-background: rgb(239 223 225);
    --color-surface: rgb(25 17 19);
    --color-on-surface: rgb(239 223 225);
    --color-surface-variant: rgb(81 67 71);
    --color-on-surface-variant: rgb(213 194 198);
    --color-outline: rgb(158 140 144);
    --color-outline-variant: rgb(81 67 71);
    --color-shadow: rgb(0 0 0);
    --color-scrim: rgb(0 0 0);
    --color-inverse-surface: rgb(239 223 225);
    --color-inverse-on-surface: rgb(55 46 48);
    --color-inverse-primary: rgb(140 74 96);
    --color-primary-fixed: rgb(255 217 226);
    --color-on-primary-fixed: rgb(58 7 29);
    --color-primary-fixed-dim: rgb(255 176 200);
    --color-on-primary-fixed-variant: rgb(112 51 73);
    --color-secondary-fixed: rgb(255 217 226);
    --color-on-secondary-fixed: rgb(43 21 28);
    --color-secondary-fixed-dim: rgb(227 189 198);
    --color-on-secondary-fixed-variant: rgb(90 63 71);
    --color-tertiary-fixed: rgb(255 220 193);
    --color-on-tertiary-fixed: rgb(46 21 0);
    --color-tertiary-fixed-dim: rgb(239 189 148);
    --color-on-tertiary-fixed-variant: rgb(98 63 32);
    --color-surface-dim: rgb(25 17 19);
    --color-surface-bright: rgb(65 55 57);
    --color-surface-container-lowest: rgb(20 12 14);
    --color-surface-container-low: rgb(34 25 28);
    --color-surface-container: rgb(38 29 32);
    --color-surface-container-high: rgb(49 40 42);
    --color-surface-container-highest: rgb(60 50 53);
  }

  :root {
    // https://tailwindcss.com/docs/box-shadow
    --shadow-small: 0 1px 2px 0 rgb(0 0 0 / 0.05);
    --shadow-large: 0 10px 15px -3px rgb(0 0 0 / 0.1),
      0 4px 6px -4px rgb(0 0 0 / 0.1);

    --brad-large: 2rem;
    --brad-standard: 1rem;
    --brad-small: 0.5rem;

    --fs-large: calc(4rem / 3);
    --fs-standard: 1rem;
    --fs-small: 0.75rem;

    // other stuff //

    --time-transition: 160ms;
    --outline: 2px solid var(--accent);
    --scrollbar-size: 0.5rem;
  }
</style>
