[package]
name = "covey"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "IO interface for the Covey application"

[lints]
workspace = true

[dependencies]
color-eyre.workspace = true
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["fs", "process"] }
tonic.workspace = true
prost.workspace = true
az.workspace = true
dirs.workspace = true
parking_lot.workspace = true
covey-schema = { path = "../covey-schema", version = "0.0.1" }
freedesktop-icons = "0.3"

[build-dependencies]
tonic-build = "0.12.3"
