use std::{process, sync::Arc, time::Duration};

use anyhow::Context;
use parking_lot::Mutex;
use tokio::{io::AsyncBufReadExt as _, task::LocalSet};

use crate::{Plugin, manifest::ManifestDeserialization as _, store::ListItemStore};

/// Starts up the server with a specified plugin implementation.
///
/// The plugin id should be `env!("CARGO_PKG_NAME")`.
///
/// This will start a single-threaded tokio runtime.
///
/// # Examples
/// See this crate's README.md for extra details.
///
/// Simple plugin with no configuration:
/// ```ignore
/// use covey_plugin::{clone_async, Action, Input, List, ListItem, Plugin, Result};
///
/// struct MyPlugin;
///
/// impl Plugin for MyPlugin {
///     // ignore configuration
///     type Config = ();
///
///     async fn new(config: Self::Config) -> Result<Self> {
///         Ok(Self)
///     }
///
///     async fn query(&self, query: String) -> Result<List> {
///         // do some logic here...
///         Ok(List::new(vec![
///             ListItem::new("list item title")
///                 .with_description("a description")
///                 // define callbacks that will be triggered when
///                 // the user activates a command.
///                 // this method is defined an extension trait
///                 // generated by `include_manifest!()`.
///                 .on_activate(async move || {
///                     Ok([Action::Close, Action::Copy("wahoo")])
///                 })
///                 // you will often need to clone values into
///                 // the callback. use the helper macro to make
///                 // this easier.
///                 .on_complete(clone_async!(query, || {
///                     Ok(Input::new(query))
///                 }))
///         ]))
///     }
/// }
///
/// // generates types from reading `../manifest.toml`.
/// // also defines an extension trait for methods like `.on_activate`.
/// covey_plugin::include_manifest!();
///
/// fn main() {
///     // this will run the server.
///     // it requires the name of the binary to be passed in.
///     // use `env!` to get it from the cargo project.
///     covey_plugin::run_server::<Open>(env!("CARGO_BIN_NAME"))
/// }
/// ```
pub fn run_server<T: Plugin>(plugin_id: &'static str) -> ! {
    crate::PLUGIN_ID
        .set(plugin_id)
        .expect("plugin id should only be set from main");

    let result = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| anyhow::anyhow!(e))
        .and_then(|rt| {
            let set = LocalSet::new();
            let _guard = set.enter();
            rt.block_on(set.run_until(main::<T>()))
        });

    match result {
        Ok(()) => process::exit(0),
        Err(e) => {
            println!("{e:#}");
            process::exit(1)
        }
    }
}

async fn main<T: Plugin>() -> anyhow::Result<()> {
    let manifest_json = std::env::args()
        .nth(1)
        .context("JSON manifest must be provided as the first argument to this plugin")?;
    let plugin = T::new(T::Config::try_from_input(&manifest_json)?).await?;
    let plugin = Arc::new(plugin);

    let list_item_store = Arc::new(Mutex::new(ListItemStore::new()));

    let mut stdin_lines = tokio::io::BufReader::new(tokio::io::stdin()).lines();

    loop {
        // auto kill this process after 24h of inactivity
        match tokio::time::timeout(Duration::from_secs(24 * 60 * 60), stdin_lines.next_line()).await
        {
            // Timed out
            Err(timeout) => {
                eprintln!("{timeout:?} passed without new query. shutting down.");
                return Ok(());
            }
            // `next_line` failed
            Ok(Err(e)) => anyhow::bail!(e),
            // No more lines
            Ok(Ok(None)) => {
                eprintln!("stdin closed");
                return Ok(());
            }
            // Got a line within the time limit
            Ok(Ok(Some(line))) => {
                handle_request_line(Arc::clone(&plugin), Arc::clone(&list_item_store), line)?
            }
        }
    }
}

fn handle_request_line<T: Plugin>(
    plugin: Arc<T>,
    list_item_store: Arc<Mutex<ListItemStore>>,
    line: String,
) -> anyhow::Result<()> {
    let covey_proto::covey_request::Request { id, request } =
        serde_json::from_str(&line).context("malformed request from covey")?;

    // Handling the request may take some time, don't block!
    // Allow handling multiple requests at once by spawning a new task.
    tokio::task::spawn_local(async move {
        match request {
            covey_proto::covey_request::Body::Query(query) => {
                match plugin.query(query.text).await {
                    Ok(list) => {
                        let proto_list = list_item_store.lock().store_query_result(list);
                        let response =
                            covey_proto::plugin_response::Response::set_list(id, proto_list);
                        response.write_to_stdout();
                    }
                    Err(e) => {
                        let response = covey_proto::plugin_response::Response::display_error(
                            id,
                            format!("{e:#}"),
                        );
                        response.write_to_stdout();
                    }
                };
            }
            covey_proto::covey_request::Body::Activate(covey_proto::covey_request::Activate {
                item_id,
                command_id,
            }) => {
                match list_item_store.lock().fetch_callbacks_of(item_id) {
                    Some(callbacks) => {
                        let (tx, mut rx) = tokio::sync::mpsc::unbounded_channel();
                        let menu = crate::Menu { sender: tx };

                        let call_command_task = callbacks.call_command(&command_id, menu);
                        let forward_to_covey_task = async {
                            while let Some(action) = rx.recv().await {
                                let response =
                                    covey_proto::plugin_response::Response::perform_action(
                                        id, action,
                                    );
                                response.write_to_stdout();
                            }
                        };

                        tokio::join!(call_command_task, forward_to_covey_task);
                    }
                    None => {
                        eprintln!("failed to fetch callback of list item {item_id:?}")
                    }
                };
            }
        };
    });
    Ok(())
}
