use std::{process, sync::Arc};

use anyhow::Context;
use parking_lot::Mutex;
use tokio::{io::AsyncBufReadExt as _, task::LocalSet};

use crate::{
    Plugin, manifest::ManifestDeserialization as _, plugin::BlockingPluginWrapper,
    store::CommandMap,
};

/// Starts up the server with a specified plugin implementation.
///
/// The plugin id should be `env!("CARGO_PKG_NAME")`.
///
/// This will start a single-threaded tokio runtime.
///
/// # Examples
/// See this crate's README.md for extra details.
///
/// Simple plugin with no configuration:
/// ```ignore
/// use covey_plugin::{clone_async, Action, Input, List, ListItem, Plugin, Result};
///
/// struct MyPlugin;
///
/// impl Plugin for MyPlugin {
///     // ignore configuration
///     type Config = ();
///
///     async fn new(config: Self::Config) -> Result<Self> {
///         Ok(Self)
///     }
///
///     async fn query(&self, query: String) -> Result<List> {
///         // do some logic here...
///         Ok(List::new(vec![
///             ListItem::new("list item title")
///                 .with_description("a description")
///                 // define callbacks that will be triggered when
///                 // the user activates a command.
///                 // this method is defined an extension trait
///                 // generated by `include_manifest!()`.
///                 .on_activate(async move || {
///                     Ok([Action::Close, Action::Copy("wahoo")])
///                 })
///                 // you will often need to clone values into
///                 // the callback. use the helper macro to make
///                 // this easier.
///                 .on_complete(clone_async!(query, || {
///                     Ok(Input::new(query))
///                 }))
///         ]))
///     }
/// }
///
/// // generates types from reading `../manifest.toml`.
/// // also defines an extension trait for methods like `.on_activate`.
/// covey_plugin::include_manifest!();
///
/// fn main() {
///     // this will run the server.
///     // it requires the name of the binary to be passed in.
///     // use `env!` to get it from the cargo project.
///     covey_plugin::run_server::<Open>(env!("CARGO_BIN_NAME"))
/// }
/// ```
pub fn run_server<T: Plugin>(plugin_id: &'static str) -> ! {
    crate::PLUGIN_ID
        .set(plugin_id)
        .expect("plugin id should only be set from main");

    let result = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| anyhow::anyhow!(e))
        .and_then(|rt| {
            let set = LocalSet::new();
            let _guard = set.enter();
            rt.block_on(set.run_until(main::<T>()))
        });

    match result {
        Ok(()) => process::exit(0),
        Err(e) => {
            println!("{e:#}");
            process::exit(1)
        }
    }
}

/// Starts up the server with a specified plugin implementation.
///
/// The plugin id should be `env!("CARGO_PKG_NAME")`.
///
/// This should be used for plugins where queries are computationally expensive
/// and cannot be made asynchronous very easily. Each
/// [`query`](Plugin::query) call is spawned into a thread pool.
///
/// See docs on [`run_server`] for more details.
pub fn run_server_blocking<T: Plugin + Send + Sync>(plugin_id: &'static str) -> ! {
    run_server::<BlockingPluginWrapper<T>>(plugin_id)
}

async fn main<T: Plugin>() -> anyhow::Result<()> {
    let manifest_json = std::env::args()
        .nth(1)
        .context("JSON manifest must be provided as the first argument to this plugin")?;
    let plugin = T::new(T::Config::try_from_input(&manifest_json)?).await?;
    let plugin = Arc::new(plugin);

    let command_map = Arc::new(Mutex::new(CommandMap::new()));

    let mut stdin_lines = tokio::io::BufReader::new(tokio::io::stdin()).lines();

    loop {
        match stdin_lines.next_line().await {
            Err(e) => anyhow::bail!(e),
            // No more lines
            Ok(None) => {
                eprintln!("stdin closed");
                return Ok(());
            }
            Ok(Some(line)) => {
                handle_request_line(Arc::clone(&plugin), Arc::clone(&command_map), &line)?
            }
        }
    }
}

fn handle_request_line<T: Plugin>(
    plugin: Arc<T>,
    command_map: Arc<Mutex<CommandMap>>,
    line: &str,
) -> anyhow::Result<()> {
    let covey_proto::Request {
        id: request_id,
        request,
    } = serde_json::from_str(line).context("malformed request from covey")?;

    // Handling the request may take some time, don't block!
    // Allow handling multiple requests at once by spawning a new task.
    tokio::task::spawn_local(async move {
        match request {
            covey_proto::RequestBody::Query(query) => {
                match plugin.query(query.text).await {
                    Ok(list) => {
                        let proto_list = command_map.lock().store_query_result(list);
                        let response = covey_proto::Response::set_list(request_id, proto_list);
                        println!("{}", response.serialize());
                    }
                    Err(e) => {
                        let response =
                            covey_proto::Response::display_error(request_id, format!("{e:#}"));
                        println!("{}", response.serialize());
                    }
                };
            }
            covey_proto::RequestBody::Activate(covey_proto::RequestActivate {
                target_id,
                command_id,
            }) => {
                let callback =
                    command_map
                        .lock()
                        .target_callbacks(target_id)
                        .and_then(|(visit_id, c)| {
                            Some((visit_id.cloned(), c.get_callback(&command_id).cloned()?))
                        });

                match callback {
                    Some((visit_id, callback)) => {
                        if let Some(visit_id) = visit_id {
                            crate::rank::Visits::update_file_with_visit(visit_id)
                        };
                        callback(crate::Menu { request_id }).await;
                    }
                    None => {
                        eprintln!("failed to fetch {command_id:?} of {target_id:?}")
                    }
                };
            }
        }
    });
    Ok(())
}
