[package]
name = "covey-plugin"
version = "0.1.0"
edition.workspace = true
# 1.85 required for async closures / AsyncFn.
# this might be outdated, im not really gonna update this.
# i only guarantee that this runs on latest stable.
rust-version = "1.85"

[lints]
workspace = true

[dependencies]
prost.workspace = true
tokio = { workspace = true, features = ["rt"] }
tokio-stream = { version = "0.1.16", default-features = false, features = [
    "net",
] }
tonic.workspace = true
az.workspace = true
anyhow = "1.0.93"
sublime_fuzzy = "0.7.0"
time = { version = "0.3", features = ["serde"] }
parking_lot = "0.12"
covey-config = { path = "../covey-config" }
covey-config-macro = { path = "../covey-config-macro" }
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true

[build-dependencies]
tonic-build = "0.12.3"
