[package]
name = "covey-plugin"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
prost.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tokio-stream = { version = "0.1.16", default-features = false, features = [
    "net",
] }
tonic.workspace = true
az.workspace = true
anyhow = "1.0.93"
sublime_fuzzy = "0.7.0"
time = { version = "0.3", features = ["serde"] }
parking_lot = "0.12"
covey-config = { path = "../covey-config" }
covey-config-macro = { path = "../covey-config-macro" }
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true

[build-dependencies]
tonic-build = "0.12.3"
