[package]
name = "covey-plugin"
# update this separately to everything else
# but keep in sync with covey-manifest-macros
version = "0.0.1"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
# 1.85 required for async closures / AsyncFn.
# this might be outdated, im not really gonna update this.
# i only guarantee that this runs on latest stable.
rust-version = "1.85"
description = "APIs for creating Covey plugins"

[lints]
workspace = true

[dependencies]
prost.workspace = true
tokio = { workspace = true, features = ["rt"] }
tokio-stream = { version = "0.1.16", default-features = false, features = [
    "net",
] }
tonic.workspace = true
az.workspace = true
anyhow = "1.0.93"
sublime_fuzzy = "0.7.0"
time = { version = "0.3", features = ["serde"] }
parking_lot = "0.12"
covey-manifest-macros = { path = "../covey-manifest-macros", version = "0.0.1" }
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true

[build-dependencies]
tonic-build = "0.12.3"
